---
 - name: install python dependencies
   yum: name={{ item }} state=present
   with_items:
       - python
       - python-setuptools
       - python-devel
       - python-pip
 - name: upgrade setuptools
   pip: name=setuptools state=latest executable=/usr/bin/pip2
