---
 - name: install ansible compilation dependencies
   yum: name={{ item }} state=present
   with_items:
      - libffi-devel
      - openssl-devel
 - name: install ansible
   pip: name=ansible state=present executable=/usr/bin/pip2
